version: '3.1'
services:
  postrgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: actix
      POSTGRES_USER: actix
      POSTGRES_DB: actix
    ports:
      - 5432:5432 

  api:
    image: flict/todo-api
    build: .
    links:
      - postrgres
    environment:
        SERVER.HOST: 0.0.0.0
        SERVER.PORT: 7878
        PG.HOST: postrgres
        PG.PORT: 5432
        PG.USER: actix
        PG.PASSWORD: actix
        PG.DBNAME: actix
        PG.POOL.MAX_SIZE: 30
        RUST_LOG: debug
    ports:
      - 7878:7878 
    