name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: flict/todo-api-cache
    services:
      postgres:
        image: postgres:10.12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 10s --health-retries 8

    steps:
    - uses: actions/checkout@v3
    - name: Move cache
      run: mv /cache/target .
    - name: Run migrations 
      run: diesel migration run 
      env:
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    - name: Copy .env file
      run: cp .env.github .env
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
